import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Rubik } from "next/font/google";

import "./globals.css";

import { Toaster } from "@/components/ui/sonner";

const rubik = Rubik({
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Food Ordering Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={rubik.className}>
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
